### ISSUE TITLE
Widget removal not working on Linux (Ubuntu 18.04)

### ISSUE THREAD

**Issue by waitsfornone** [beeware/toga#971]
**Describe the bug**
While attempting to remove a child of a Box Widget, I get the following error: 

`AttributeError: 'Box' object has no attribute 'remove_child'`

**To Reproduce**
1. Download this repo [https://github.com/waitsfornone/hangman](url)
2. Change branch to `gtk_remove_bug`
3. Run app (only dependency is Toga)
4. Exception should bubble up from line 45 in `hangman.py`

**Expected behavior**
I expected to be able to remove the child by the reference

**Environment:**
Ubuntu 18.04 (64-bit)
Python 3.8.1
Toga 0.3.0dev22

**Comment by filyc** [comment]
Hi Folks, I see a similar error on Windows--even with Box.add, since that also potentially calls remove when adding to new parent.
