### PR TITLE
Implement `remove_child` method for widgets in winforms and GTK

### LINKED ISSUE #971: Widget removal not working on Linux (Ubuntu 18.04)
**Describe the bug**
While attempting to remove a child of a Box Widget, I get the following error: 

`AttributeError: 'Box' object has no attribute 'remove_child'`

**To Reproduce**
1. Download this repo [https://github.com/waitsfornone/hangman](url)
2. Change branch to `gtk_remove_bug`
3. Run app (only dependency is Toga)
4. Exception should bubble up from line 45 in `hangman.py`

**Expected behavior**
I expected to be able to remove the child by the reference

**Environment:**
Ubuntu 18.04 (64-bit)
Python 3.8.1
Toga 0.3.0dev22

### PR DESCRIPTION
**Pull request by obulat**
Signed-off-by: Olga <obulat@gmail.com>

Fixes #971 

When `remove` method is called on a toga widget, it calls the _impl's  `remove_child` method for each child widget. However, Winforms and GTK backends do not currently have this method. This PR adds  `remove_child` method to Winforms' base `Widget` class.

As stated in the official documentation, https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-add-to-or-remove-from-a-collection-of-controls-at-run-time, Winforms requires three steps to remove a child widget: 1. remove custom event handlers; 2. remove widget from the child widget collection; 3. release the resources used by the child widget. 
The new property of winforms base Widget class, `winforms_event_handlers`, keeps track of custom (user-added) event handlers, to remove them when `remove_child` is called.

Each widget that adds custom event handlers also appends them to its `winforms_event_handlers` in `create` method.
Also, `winforms_` method naming for custom widget event handling were renamed to correspond to the Toga event handler names.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by obulat** [comment]
I've looked more into the code, and changed the implementation of `remove_child` to match the one in cocoa: simply set the child widget's container property to None.  This is necessary when `remove` method is used to change a widgets' hierarchy when calling `add` or `insert` methods.

Is a method for deleting a child useful, though? I've kept previous implementation in case this is something we need in Toga.

**Comment by waitsfornone** [comment]
As you referenced this is my bug report.Yes, removing a child can be useful. If you define the child as its own object, you can then modify the layout of your UI by doing so. This give you two things. 1 -- you can then move it to another place at a later time in the code, 2 -- your layout does not have to take it into account.

Granted I could be missing a better way to do these things, but I think removing is a valid use case.

**Comment by freakboy3742** [comment]
@waitsfornone I don't think @obulat was questioning the need to remove widgets - looking at the patch, I believe she's asking about differentiating between "removal" and "deletion", which potentially requires different handling.

File: src/winforms/toga_winforms/widgets/button.py [hunk 1]
```diff
@@ -9,10 +9,16 @@
 class Button(Widget):
     def create(self):
         self.native = WinForms.Button()
-        self.native.Click += self.winforms_click
+        self.native.Click += self.winforms_on_press
```
Comment (freakboy3742) [inline src/winforms/toga_winforms/widgets/button.py:12]: The naming of `winforms_click` was deliberate. We've essentially got two signal types - the ones generated by Toga, and the ones generated by the native platform. `winforms_click` makes it clear that it's the Winforms `Click` handler; rather than needing to reverse engineer that the Toga name `on_press` is invoked by the Winforms `Click` event.

I agree the current code has a couple of inconsistencies on this pattern (e.g., should the handler be called `winforms_CheckChanged` or `winforms_check_changed`) - but broadly, I feel the Winforms handlers should reflect the Winforms event names.

File: src/winforms/toga_winforms/widgets/base.py [hunk 2]
```diff
@@ -75,11 +78,23 @@ def set_background_color(self, color):
...
     # INTERFACE
 
     def add_child(self, child):
         if self.container:
             child.container = self.container
 
+    def delete_child(self, child):
+        child.winforms_remove_event_handlers()
+        self.native.Controls.Remove(child.native)
+        child.native.Dispose()
```
Comment (freakboy3742) [inline src/winforms/toga_winforms/widgets/base.py:94]: I don't think a separate `delete_child()` method is required. I can't think of a meaningful way that we'd differentiate at an API level between "remove" and "delete".

We *do* need to make sure there's adequate clean up, though. The removal of event handlers and call to Dispose should probably be tied into the `__del__` handler for the impl-level widget, so when the Python garbage collector disposes of the object, those pieces are cleaned up.

That said - I'd be slightly surprised if this isn't already happening. I know the .NET guidelines say that cleanup must be done explicitly, but that's because it has a history with explicit-memory managed languages. It's entirely possible this cleanup & dispose is being done automatically by the python.NET lifecycle.

The test: Write an app that rapidly creates, add and removes children, in a loop. If we see a memory leak over time, and the GC is being invoked, then we'll definitely need to add some `__del__` handling.

File: src/winforms/toga_winforms/widgets/base.py [hunk 3]
```diff
@@ -8,6 +8,9 @@ def __init__(self, interface):
 
         self._container = None
         self.native = None
+        # `winforms_event_handlers` is used to keep track of added
+        # native event handlers to remove them when a widget is removed
+        self.winforms_event_handlers = []
```
Comment (freakboy3742) [inline src/winforms/toga_winforms/widgets/base.py:13]: I agree this is a good change; I wonder if it might be worth going "all in" here, and writing a wrapper API for managing these events? e.g., instead of expecting the user to use the Python.NET API to add the event, and *then* make sure it's added to the handler list, expose a single (toga-winforms-specific) `add_winforms_handler()` method that both registers the handler *and* adds it to the list to be managed.

File: src/winforms/toga_winforms/widgets/button.py (hunk 1 above)
Comment (obulat) [reply src/winforms/toga_winforms/widgets/button.py:12]: As a person reading the winforms backend code, the name `winforms_on_press` makes it clear to me that the native `Click` event is handled by the Toga `on_press` handler. Currently, I have to look up the `winforms_click` function to see which Toga event handler is called to handle native event.
However, I see that when debugging, it is more useful to see the distinction between Toga signals and native signals. So, I would like to finish up the housekeeping and rename the functions to get rid of inconsistencies.
I prefer the more pythonic underscore version: `winforms_check_changed`, and not `winforms_CheckChanged`, do you agree?

File: src/winforms/toga_winforms/widgets/base.py (hunk 3 above)
Comment (obulat) [reply src/winforms/toga_winforms/widgets/base.py:13]: I was sure that you would suggest a more elegant solution :) 
I will work on adding the `add_winforms_handler` after figuring out the garbage collection via test app.

Comment (freakboy3742) [reply src/winforms/toga_winforms/widgets/base.py:13]: :-) 

To be clear, though - `add_winforms_handler()` may end up not being needed at all - if Python.NET *does* do full garbage collection, then the sort of event handling we have at present (i.e., before this patch - just assigning the event hander) will be more than sufficient, as there's no need to do a coordinated clean up on deletion.

File: src/winforms/toga_winforms/widgets/base.py (hunk 2 above)
Comment (obulat) [reply src/winforms/toga_winforms/widgets/base.py:94]: I've written a [test app](https://gist.github.com/obulat/caddd0d037df92f068deb6ada9c4a6e7) that adds and removes a single button to a container in a loop. What's the best way of testing memory leaks?
Simply running the app seems to show that it does leak: when I run the loop 1000 times, the app runs for about 4 seconds, and when I set it to repeat 100000 times, the app hung.

Comment (freakboy3742) [reply src/winforms/toga_winforms/widgets/base.py:102]: Best method for tracking memory in this situation is probably the resources module: 

```
import resource

usage = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
```

That will tell you the memory allocated to the process.

If 1000x create and destroy takes about four seconds, put that logic on a button handler, and measure (and print) memory usage after every create/destroy cycle completes. If that number goes up with every press, we've got a leak. 

The number won't be _completely_ stable - it might go up and down a little - but if there's a leak, it will go up a lot - and by a reasonably predictable amount each cycle.

Comment (obulat) [reply src/winforms/toga_winforms/widgets/base.py:102]: Apparently, `resource` is Unix specific and doesn't work on Windows.

Comment (freakboy3742) [reply src/winforms/toga_winforms/widgets/base.py:102]: Ok - two alternatives are [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) (this is slower than resource, but gives a more precise memory calculation), or [gc](https://docs.python.org/3/library/gc.html) (which won't give you a literal *memory* count, but will tell you the number of objects that aren't being garbage collected, and which objects are being caught in a reference cycle).

Comment (obulat) [reply src/winforms/toga_winforms/widgets/base.py:102]: I've tried `gc.get_stats`, it returns the same result at the beginning and at the end of the loop. 
This is what I get with `tracemalloc`: 
```
20000 cycles took 33.329090099999995 seconds
[ Top 10 differences ]
<...>\AppData\Local\Programs\Python\Python37\lib\asyncio\windows_events.py:427: size=165 KiB (+165 KiB), count=41 (+41), average=4129 B
<...>\dev\beeware\toga\venv\lib\site-packages\travertino\declaration.py:174: size=95.2 KiB (+95.2 KiB), count=1610 (+1610), average=61 B
<...>\dev\beeware\toga\src\winforms\toga_winforms\app.py:86: size=58.5 KiB (+58.5 KiB), count=667 (+667), average=90 B
<...>\dev\beeware\toga\src\winforms\toga_winforms\app.py:76: size=42.7 KiB (+42.7 KiB), count=471 (+471), average=93 B
<...>\dev\beeware\toga\src\winforms\toga_winforms\window.py:110: size=37.0 KiB (+37.0 KiB), count=442 (+442), average=86 B
<...>\dev\beeware\toga\src\winforms\toga_winforms\libs\proactor.py:103: size=15.2 KiB (+15.2 KiB), count=112 (+112), average=139 B
<...>\dev\beeware\toga\src\winforms\toga_winforms\app.py:83: size=11.4 KiB (+11.4 KiB), count=105 (+105), average=112 B
<...>\dev\beeware\toga\src\winforms\toga_winforms\libs\proactor.py:99: size=8883 B (+8883 B), count=71 (+71), average=125 B
<...>\Local\Programs\Python\Python37\lib\asyncio\windows_events.py:661: size=5936 B (+5936 B), count=44 (+44), average=135 B
<...>\AppData\Local\Programs\Python\Python37\lib\asyncio\windows_events.py:424: size=5904 B (+5904 B), count=41 (+41), average=144 B
```
I'm not sure how to interpret it. [Here is the app code](https://gist.github.com/obulat/caddd0d037df92f068deb6ada9c4a6e7)

File: src/winforms/toga_winforms/widgets/button.py (hunk 1 above)
Comment (obulat) [reply src/winforms/toga_winforms/widgets/button.py]: I've renamed handlers in #44923c2

File: src/winforms/toga_winforms/widgets/base.py (hunk 2 above)
Comment (freakboy3742) [reply src/winforms/toga_winforms/widgets/base.py:102]: I've taken a look at this - and it looks like we've got a deeper slow leak. 

Firstly - the really useful method (for our purposes) is [`get_traced_memory()`](https://docs.python.org/3/library/tracemalloc.html#tracemalloc.get_traced_memory). That gives you the current and peak memory allocation of your process (since you made the call to `tracemalloc.start()`). 

Another way to check memory usage is to open the Windows Resource Monitor (Control panel > Administrative tools). That won't log memory to console, but it will give you the OS-level view of how much memory is being used.

Using your test harness as a starting point, and adding in a call to `get_traced_memory()`, I've found some interesting things:

1. Yes, it looks like we've got a leak. I see a significant jump after the 20k iterations.

2. The leak gets a lot worse if you recreate the widget on each iteration. Your test harness creates the dummy button once, and then adds and removes it in rapid succession. If you create a *new* button every time, you see a faster leak.

3. AFAICT, the leak isn't fixed by manually performing the disposal process you've suggested in delete_child. I *think* memory is being cleaned up by the normal Python garbage collector... however, this is a little hard for me to confirm, because...

4. The leak may *not* be related to widget handling at all. If you just leave the app open and do nothing, you'll see in the Resource monitor there's a slow increase in memory usage over time. This is almost certainly related to the asyncio handling; something is accumulating over time.

On that basis, I'm inclined to say we shouldn't worry about the event handling cleanup code for now. We clearly have other memory leaks that are much more significant. Once we've got a handle on the background leak, we can take a closer look at individual widget leaks.

File: src/winforms/toga_winforms/widgets/base.py (hunk 3 above)
Comment (obulat) [reply src/winforms/toga_winforms/widgets/base.py]: I've removed all `add_winforms_handler` calls as they seem unnecessary at the moment.

File: src/winforms/toga_winforms/widgets/base.py (hunk 2 above)
Comment (obulat) [reply src/winforms/toga_winforms/widgets/base.py]: Thank you for such detailed answer!

So, for now simply setting container to `None` when removing a child widget is fine, isn't it?

Comment (freakboy3742) [reply src/winforms/toga_winforms/widgets/base.py]: I think so, yes.
