### ISSUE TITLE
toga_web fails to start because it imports a non-existent pyscript.web module; docs + 0.5.3 top-level Box regression

### ISSUE THREAD

**Issue by NADOOITChristophBa** [beeware/toga#4088]
### Describe the bug

Running any Toga app with the web backend immediately crashes before the UI can render. The backend imports pyscript.web, but none of the released PyScript wheels contain that module. In addition, after upgrading from 0.5.2 → 0.5.3, toga.Box disappeared from the top-level namespace, so code that relied on toga.Box now raises AttributeError. The documentation pages for the container widgets in the “latest” docs build also 404, which makes it hard to confirm whether this is an intentional change. https://toga.beeware.org/en/latest/reference/api/containers/box/

### Steps to reproduce

1. Go to a Toga project (any minimal app repro will do).
2. Run pip install toga==0.5.3 toga-web==0.5.3 pyscript==0.3.3.
3. Run the app with TOGA_BACKEND=toga_web python -m my_app.
4. See the crash:

RuntimeError: The backend specified by TOGA_BACKEND ('toga_web') could not be loaded
ModuleNotFoundError: No module named 'pyscript.web'

(Separately, any import of toga.Box in 0.5.3 now raises AttributeError: module 'toga' has no attribute 'Box'.)

### Expected behavior

The Toga web backend should load and render the app (or at least guide users to install the required dependencies). toga.Box should remain importable via toga.Box as in 0.5.2. Documentation pages for container widgets (e.g., /reference/api/containers/box.html in the “latest” docs) should be reachable.

### Screenshots

- Web backend loads, serves the UI, or at least provides guidance on missing dependencies.
- toga.Box remains available at toga.Box (as in 0.5.2) or the docs announce the new import path.
- Container documentation at https://toga.readthedocs.io/en/latest/reference/api/containers/box.html is accessible.

### Environment

- **Operating system:** macOS 15.6.1 (24G90) on Apple Silicon  
- **Python:** 3.11.14 (venv)  
- **Toga stack (currently installed):**  
  - `toga==0.5.2` (downgraded from 0.5.3 to avoid the `toga.Box` regression)  
  - `toga-core==0.5.2`  
  - `toga-cocoa==0.5.2`  
  - `toga-web==0.5.2`  
  - `travertino==0.5.2`  
- **PyScript:** 0.3.3 (latest PyPI release – lacks `pyscript.web`)  
- **Briefcase:** 0.3.27.dev27+g7c9a57c7f (CLI `briefcase --version` currently reports 0.3.21 due to the dev build)  
- **uv:** 0.7.3 (3c413f74b, 2025‑05‑07)  
- **Other tooling:** running from a local virtualenv; no PyInstaller involved for this repro.

### Logs

```
Briefcase Log:
[15:22:29] [nadoo_launchpad] Starting in dev mode...
>>> Running Command:
>>>     /Users/christophbackhaus/Documents/GitHub/NADOO-Launchpad/.venv/bin/python3 -c 'import runpy,
sys;sys.path.pop(0);sys.argv.extend([]);runpy.run_module("nadoo_launchpad", run_name="__main__", alter_sys=True)'
>>> Working Directory:
>>>     /Users/christophbackhaus
>>> Environment Overrides:
>>>     PYTHONPATH=/Users/christophbackhaus/Documents/GitHub/NADOO-Launchpad/nadoo_launchpad/src
>>>     PYTHONUNBUFFERED=1
>>>     PYTHONDEVMODE=1
>>>     PYTHONUTF8=1
=======================================================================
2026-01-17 15:22:29 - nadoo_launchpad - INFO - Logging configured. Log file:
/Users/christophbackhaus/Documents/GitHub/NADOO-Launchpad/nadoo_launchpad/logs/nadoo_launchpad_20260117_152229.log
2026-01-17 15:22:30 - ... (Launchpad init logs)

Traceback (most recent call last):
  File ".../site-packages/toga/platform.py", line 69, in get_platform_factory
    factory = importlib.import_module(f"{backend_value}.factory")
  ...
  File ".../site-packages/toga_web/libs.py", line 12, in <module>
    from pyscript.web import document
ModuleNotFoundError: No module named 'pyscript.web'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../nadoo_launchpad/src/nadoo_launchpad/__main__.py", line 29, in <module>
    main().main_loop()
  ...
  File ".../site-packages/toga/platform.py", line 78, in get_platform_factory
    raise RuntimeError(
RuntimeError: The backend specified by TOGA_BACKEND ('toga_web') could not be loaded (No module named 'pyscript.web'). It should be one of: 'toga_cocoa', 'toga_web'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  ...
  File "/Users/christophbackhaus/Documents/GitHub/NADOO-Launchpad/nadoo_launchpad/src/nadoo_launchpad/__main__.py", line 32, in <module>
    briefcase_log_file.getLogger(__name__).exception("Unhandled exception in main loop")
AttributeError: 'PosixPath' object has no attribute 'getLogger'

Problem running app nadoo_launchpad.
Saving log... started
Saving log... done
```

**Comment by NADOOITChristophBa** [comment]
Update / Apology
Sorry for the noise — we tracked this down to our test environment, not Toga itself.

Root cause on our side:
- A test module was globally patching `sys.modules["toga"]`, which contaminated subsequent imports in the test suite.
- We also ensured `TOGA_BACKEND` is cleared during tests so the web backend isn't forced.

After isolating the mock and cleaning the env, the Toga‑related errors disappeared in our suite.
The only remaining observation: the [Box](https://toga.readthedocs.io/en/latest/reference/api/containers/box.html) docs link in the latest docs still seems broken (if you want, we can open a separate doc issue).

**Comment by freakboy3742** [comment]
> Update / Apology Sorry for the noise — we tracked this down to our test environment, not Toga itself.

Whew! For a moment there I was really worried we'd messed up the web backend :-)

> The only remaining observation: the [Box](https://toga.readthedocs.io/en/latest/reference/api/containers/box.html) docs link in the latest docs still seems broken (if you want, we can open a separate doc issue).

Thanks for letting us know. We recently did a light refactor of the API docs, and included some redirect rules so old URLs would continue to work... it looks like we messed up the configuration so that all the container widgets are redirecting to themselves. We'll get a fix up shortly; no extra issue needed

**Comment by freakboy3742** [comment]
FYI - the documentation issue should now be resolved (see #4095)
