### ISSUE TITLE
DateInput not working on Android 7.1.2

### ISSUE THREAD

**Issue by BoredManCodes** [beeware/toga#2322]
### Describe the bug

The date_and_time example fails to run on android 7.1.2

### Steps to reproduce

1. Load `date_and_time` example
2. Run `briefcase run android -u`
3. Select either Android 7.1.2 physical device or emulator
4. App crashes with following error:
[Device log output.txt](https://github.com/beeware/toga/files/13826814/Device.log.output.txt)

### Expected behavior

Date input works as expected 

### Environment

- Operating System: Android 7.1.2, Built on Windows 11 23H2 (Build 22631.2861)
- Android devices: VT-7 Pro, emulator - ![image](https://github.com/beeware/toga/assets/78893529/54dcd80e-ce3b-4b04-a3f1-8a8361750827)
- Python version: Python 3.10.4
- Software versions:
  - Briefcase: 0.3.16
  - Toga: 0.4.1

**Comment by freakboy3742** [comment]
Thanks for the report; unfortunately, I can't reproduce the problem locally with an Android 25 emulator (started with `briefcase run android -d '{"avd": "beePhone25", "skin":"pixel_3a", "system_image": "system-images;android-25;default;arm64-v8a"}`)

I get *part* of the stack trace that you've shown: 
```
Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
```

That part makes sense - `OnUnhandledKeyEventListener` was added in API 28. It appears to be be caused by the version of the AppCompat library that we're using. 

However, this doesn't cause the rest of the crash (the `OverflowError: timestamp out of range for platform time_t` part).

**Comment by djb200** [comment]
Hey,
I recognized the same issue for Android 14.

**Comment by freakboy3742** [comment]
@djb200 Can you clarify which part of the "same issue" you're seeing? The NoClassDefFound error? The OverflowError? Both? Neither, but you're having problems with DateInput?

**Comment by djb200** [comment]
I got the OverflowError: timestamp out of range for platform time_t  Error.

**Comment by mhsmith** [comment]
With the `date_and_time` example, or with your own code? If your own code, please post it here.

And either way, did the error happen immediately on startup, or did you have to do something else?

**Comment by mhsmith** [comment]
Also, what Python version are you using?
