### ISSUE TITLE
AttributeError: 'CSS' object has no attribute 'bind'

### ISSUE THREAD

**Issue by ScriptHosT12** [beeware/toga#701]
## Expected Behavior

It would just nicely run like the examples

## Current Behavior

```...>python -m main
Traceback (most recent call last):
  File "...\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "...\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "...\main.py", line 24, in <module>
    main().main_loop()
  File "...\AppData\Local\Programs\Python\Python36-32\lib\site-packages\toga_winforms\app.py", line 49, in main_loop
    self._startup()
  File "...\AppData\Local\Programs\Python\Python36-32\lib\site-packages\toga_winforms\app.py", line 41, in _startup
    self.startup()
  File "...\AppData\Local\Programs\Python\Python36-32\lib\site-packages\toga\interface\app.py", line 144, in startup
    self.main_window.content = self._startup_method(self)
  File "...\main.py", line 9, in build
    box = toga.Box()
  File "...\AppData\Local\Programs\Python\Python36-32\lib\site-packages\toga_winforms\widgets\box.py", line 10, in __init__
    super().__init__(id=id, style=style, children=children)
  File "...\AppData\Local\Programs\Python\Python36-32\lib\site-packages\toga\interface\widgets\box.py", line 21, in __init__
    super().__init__(id=id, style=style, children=children)
  File "...\AppData\Local\Programs\Python\Python36-32\lib\site-packages\toga\interface\widgets\base.py", line 144, in __init__
    self.style = CSS()
  File "...\AppData\Local\Programs\Python\Python36-32\lib\site-packages\toga\interface\widgets\base.py", line 170, in style
    self._style = value.bind(self)
AttributeError: 'CSS' object has no attribute 'bind'
``` 
## Steps to reproduce

1. Run the very first example

## Your Environment

global enviornment

* Python Version
3.6.4
* Operating System and Version

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [x] Windows - version: 7
  - [ ] Other - name:  - version:

* Toga Target
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
It looks like you're possibly running an old tutorial for the 0.2 branch of code. That branch didn't work well on Windows; the 0.3 branch has much better support.

Can you confirm:
* Which version of the tutorial you are running (e.g., by providing a URL), and
* Whether your installation of toga was `pip install toga` or `pip install --pre toga`?

(For the record - the latter is the version that will work on Windows)

**Comment by erwindewolf** [comment]
It looks like a loop. --pre toga can't find module toga.django So the advice is to downgrade to 0.2.15.
If you downgrade: it get the problem 'CSS' object has no attribute 'bind' So the advice is to upgrade to --pre toga. It looks like a loop.
Iḿ working with the Linux distro. Please help

**Comment by grantslay** [comment]
I ran into this issue as well on Linux. 
Simply did a `pip install toga-demo` and it got version 0.2.15 
I'll try using the 0.3 branch.

**Comment by erwindewolf** [comment]
Thank you grantslay, I'll tryed that. But version 0.2.15 installs nowerdays an upgraded css-manager   Colosseum 2.0. instead of 1.6. If downgrade Colosseum I run in problems with other apps.
Is there anywhere a requirements.txt with the exact Versions needed? Ones running I can problebly get a grip on development. Thanks

**Comment by julenl** [comment]
The partial workaround of @erwindewolf worked for me:

    pip uninstall colosseum
    pip install colosseum==0.1.6
    python3 setup.py django -s

And everything runs just fine. Luckily I don't have other dependencies with `colosseum`.

**Comment by freakboy3742** [comment]
Closing on the basis that is appears to be an error related to the 0.2 branch.
